# Generated by Django 5.1.6 on 2025-03-01 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(blank=True, max_length=20)),
                ('member_fname', models.CharField(max_length=32)),
                ('member_mname', models.CharField(blank=True, max_length=32)),
                ('member_lname', models.CharField(blank=True, max_length=32)),
                ('member_info', models.CharField(blank=True, max_length=128)),
                ('member_role', models.CharField(choices=[('admin', 'System Admin'), ('manager', 'Manager'), ('drone', 'Drone Controller'), ('analyst', 'Data Analyst'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('member_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
